### ISSUE TITLE
v2 - challenge2 doesn't use dot notation to extend app, uses an `app` variable

### ISSUE THREAD

**Issue by tgaff** [SF-WDI-LABS/intro_angular_challenges#6]
Style guide:  https://github.com/SF-WDI-LABS/angular_style_guide#use-dot-chaining-to-build-the-app-rather-than-repetition-of-an-app-variable

This does make it a bit easier to work with initially though.  Maybe OK?

**Comment by nathanallen** [comment]
Yeah, I keep going back and forth on this one... I think let's keep it with `app` assignment for now as it makes for easier copy-pasting, and is less brittle.
